### ISSUE TITLE
error converting subtitles NodeError: Callback must be a function

### ISSUE THREAD

**Issue by sergiomb2** [jasonrojas/node-captions#27]
https://github.com/jasonrojas/node-captions/blob/57709ecb8428063a6ad9b2919ff57155be0b99a7/lib/srt.js#L95

```
error converting subtitles NodeError: Callback must be a function
    at maybeCallback (fs.js:140:9)
    at Object.fs.writeFile (fs.js:1258:14)
    at Object.parse (/usr/share/node_modules/node-captions/lib/srt.js:95:20)
```

replacing by `return callback;` as suggested in https://stackoverflow.com/a/44856183/778517 fixes this error ... 

`node -v`

v8.11.4

**Comment by jasonrojas** [comment]
```
Last login: Tue Sep 18 14:49:34 on ttys001
mkdir 09/18/18 14:55:32 [ /Users/jrojas ]
[jrojas-mac]  (2.14)$ cd code/tmp/
09/18/18 14:55:34 [ /Users/jrojas/code/tmp ]
[jrojas-mac]  (2.14)$ mkdir testcaptions
09/18/18 14:55:38 [ /Users/jrojas/code/tmp ]
[jrojas-mac]  (2.04)$ cd !$
cd testcaptions
09/18/18 14:55:39 [ /Users/jrojas/code/tmp/testcaptions ]
[jrojas-mac]  (2.04)$ nvm use 8.11.4
N/A: version "8.11.4 -> N/A" is not yet installed.

You need to run "nvm install 8.11.4" to install it before using it.
09/18/18 14:55:49 [ /Users/jrojas/code/tmp/testcaptions ]
[jrojas-mac]  (1.96)$ nvm install !$
nvm install 8.11.4
Downloading and installing node v8.11.4...
Downloading https://nodejs.org/dist/v8.11.4/node-v8.11.4-darwin-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with shasum -a 256
Checksums matched!
Now using node v8.11.4 (npm v5.6.0)
09/18/18 14:56:04 [ /Users/jrojas/code/tmp/testcaptions ]
[jrojas-mac]  (3.08)$ nvm use 8.11.4
Now using node v8.11.4 (npm v5.6.0)
09/18/18 14:56:23 [ /Users/jrojas/code/tmp/testcaptions ]
[jrojas-mac]  (2.87)$ npm install node-captions --save
npm WARN saveError ENOENT: no such file or directory, open '/Users/jrojas/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/jrojas/package.json'
npm WARN jrojas No description
npm WARN jrojas No repository field.
npm WARN jrojas No README data
npm WARN jrojas No license field.

+ node-captions@0.4.6
added 3 packages in 2.402s
09/18/18 14:56:28 [ /Users/jrojas/code/tmp/testcaptions ]
[jrojas-mac]  (2.72)$ vi test.js
09/18/18 14:58:13 [ /Users/jrojas/code/tmp/testcaptions ]
[jrojas-mac]  (1.96)$ vim test.srt
09/18/18 14:58:22 [ /Users/jrojas/code/tmp/testcaptions ]
[jrojas-mac]  (1.97)$ node test.js
ACTION NEEDED: require('iconv-lite').extendNodeEncodings() is not supported in your version of Node
See more info at https://github.com/ashtuchkin/iconv-lite/wiki/Node-v4-compatibility
(node:40314) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
09/18/18 14:58:25 [ /Users/jrojas/code/tmp/testcaptions ]
[jrojas-mac]  (1.97)$ ls
out.srt  test.js  test.srt
09/18/18 14:58:42 [ /Users/jrojas/code/tmp/testcaptions ]
[jrojas-mac]  (1.83)$ cat out.srt
1
00:00:01,500 --> 00:00:02,500
<i>Tonight's the night.</i>

2
00:00:03,000 --> 00:00:15,000
<i>And it's going to happen</i>
again and again --
09/18/18 14:58:45 [ /Users/jrojas/code/tmp/testcaptions ]
[jrojas-mac]  (1.83)$ cat test.srt
1
00:00:00,000 --> 00:00:01,500
For www.forom.com

2
00:00:01,500 --> 00:00:02,500
<i>Tonight's the night.</i>

3
00:00:03,000 --> 00:00:15,000
<i>And it's going to happen
again and again --</i>
09/18/18 14:58:49 [ /Users/jrojas/code/tmp/testcaptions ]
[jrojas-mac]  (1.76)$ cat test.js
var captions = require('node-captions'),
    fs = require('fs');
captions.srt.read('./test.srt', {}, function (err, data) {
    if (err) { throw err; }
    fs.writeFile('./out.srt', captions.srt.generate(captions.srt.toJSON(data), function(err, result) {
        if (err) { throw err; }
    }));
});
09/18/18 14:58:55 [ /Users/jrojas/code/tmp/testcaptions ]
[jrojas-mac]  (1.70)$
```



Ran through the sample code and used a test SRT file I found on google using the version of node you specified and I don't have the same issue.

**Comment by sergiomb2** [comment]
Hi, thanks for the snippet.  
While with captions.srt.read works , it seems to me that captions.srt.parse fails , example: 

```
var captions = require('node-captions'),
fs = require('fs');
var srtFile = fs.readFileSync('./test.srt');
captions.srt.parse(srtFile, function (err, data) {
    if (err) { throw err; }
    fs.writeFile('./out.srt', captions.srt.generate(captions.srt.toJSON(data), function(err, result) {
        if (err) { throw err; }
    }));
});
```

**Comment by sergiomb2** [comment]
@TonyGermaneri ok could you do snippet ? with my example , I'm not an expert in js

**Comment by sergiomb2** [comment]
@TonyGermaneri  ok I could find fix the problem thanks for your time .

something like
```
var captions = require('node-captions'),
fs = require('fs');
fs.readFile(srtPath, {}, function(err, srtFile) {
    captions.srt.parse(srtFile, function (err, data) {
        if (err) { throw err; }
        fs.writeFile('./out.srt', captions.srt.generate(captions.srt.toJSON(data), function(err, result) {
            if (err) { throw err; }
        }));
  });
});

```
